language: bash

sudo: false

addons:
  apt:
    sources:
    - debian
    packages:
    - shellcheck

script:
 - shellcheck -s bash ./watch-srv.sh
 - shellcheck -s bash ./watch-srv-en.sh

notifications:
    webhooks:
